name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Deploy
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: deploy
